providers:
  docker:
    defaultRule: Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)
  file:
    directory: /etc/dokploy/traefik/dynamic
    watch: true
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
api:
  insecure: true
