name: Pull request
on:
  pull_request:
    branches:
      - main
      - canary
  push:
    branches:
      - feat/monorepo
env:
  HUSKY: 0
jobs:
  build-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.18.0]
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.5.0 # Ajusta esta versión a la que estés usando localmente

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Show installed packages
        run: |
          echo "Installed packages:"
          pnpm list

      - name: Run type check
        run: |
          echo "Running type check..."
          pnpm run dokploy:check

      - name: Upload typecheck log
        uses: actions/upload-artifact@v3
        with:
          name: typecheck-log
          path: apps/dokploy/typecheck_output.log

      - name: Run Build
        run: |
          cd apps/dokploy
          pnpm run build

      - name: Run Tests
        run: |
          cd apps/dokploy
          pnpm run test

      # Comentado por ahora, descomenta si necesitas estos pasos
      # - name: Run commitlint
      #   run: pnpm commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      # - name: Run format and lint
      #   run: pnpm biome ci
